baseURL: http://techmyth.github.io/
languageCode: en-us
copyright: "2022 Jonathan Colon All rights reserved"
title: TechMyth
theme: "PaperMod"

author:
  name: Jonathan Colon

DefaultContentLanguage: "en"

googleAnalytics: G-H243NQ4V8N

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

languages:
  es:
    languageName: Spanish
    menu:
      main:
      - identifier: home
        name: Home
        params:
          class: highlight-menu-item
        url: /
        weight: 1
      - identifier: posts
        name: Publicaciones
        params:
          class: highlight-menu-item
        url: /posts
        weight: 2
      - identifier: projects
        name: Proyectos
        params:
          class: highlight-menu-item
        url: /projects
        weight: 3
      - identifier: about
        name: Sobre mí
        params:
          class: highlight-menu-item
        url: /about
        weight: 4
      - identifier: github
        name: github
        pre: <i class='fa fa-heart'></i>
        params:
          class: highlight-menu-item
        url: https://github.com/rebelinux
        weight: 5
    title: TechMyth
    weight: 2
  en:
    languageName: English
    menu:
      main:
      - identifier: home
        name: Home
        params:
          class: highlight-menu-item
        url: /
        weight: 1
      - identifier: posts
        name: Posts
        params:
          class: highlight-menu-item
        url: /posts
        weight: 2
      - identifier: projects
        name: Projects
        params:
          class: highlight-menu-item
        url: /projects
        weight: 3
      - identifier: about
        name: About me
        pre: <i class='fa fa-heart'></i>
        params:
          class: highlight-menu-item
        url: /about
        weight: 4
      - identifier: github
        name: github
        pre: <i class='fa fa-heart'></i>
        params:
          class: highlight-menu-item
        url: https://github.com/rebelinux
        weight: 5
    title: TechMyth
    weight: 1

params:
  env: production
  description: "System Engineer in pyjama"
  author: Jon Colon
  defaultTheme: auto
  disableThemeToggle: false
  ShowFullTextinRSS: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  disableSpecial1stPost: false
  socialIcons:
  - name: "kofi"
    url: "https://ko-fi.com/F1F8DEV80"
  - name: "twitter"
    url: "https://twitter.com/jcolonfzenpr"
  - name: "rss"
    url: "https://techmyth.github.io/index.xml"
  label:
    text: "TechMyth"
    icon: /img/home_logo.webp
    iconHeight: 35
  editPost:
    URL: "https://github.com/techmyth/techmyth.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

outputs:
  home:
      - HTML
      - RSS
