baseURL: http://techmyth.github.io/
languageCode: en-us
title: TechMyth
theme: "PaperMod"

DefaultContentLanguage: "en"

googleAnalytics: G-H243NQ4V8N

languages:
  es:
    languageName: Spanish
    menu:
      main:
      - identifier: blog
        name: Blog
        params:
          class: highlight-menu-item
        url: /
        weight: 1
      - identifier: about
        name: Sobre Mí
        params:
          class: highlight-menu-item
        url: /about
        weight: 2
    title: TechMyth
    weight: 2
  en:
    languageName: English
    menu:
      main:
      - identifier: blog
        name: Blog
        params:
          class: highlight-menu-item
        url: /
        weight: 1
      - identifier: about
        name: About
        params:
          class: highlight-menu-item
        url: /about
        weight: 2
    title: TechMyth
    weight: 1

params:
  defaultTheme: dark
  disableThemeToggle: true
  socialIcons:
  - name: "kofi"
    url: "https://ko-fi.com/F1F8DEV80"
  - name: "twitter"
    url: "https://twitter.com/jcolonfzenpr"
