baseURL: http://techmyth.github.io/
languageCode: en-us
title: TechMyth
theme: "PaperMod"

languages:
  es:
    title: TechMyth
    weight: 2
  en:
    title: TechMyth
    weight: 1

params:
  defaultTheme: dark
  disableThemeToggle: true
  socialIcons:
  - name: "kofi"
    url: "https://ko-fi.com/F1F8DEV80"
  - name: "twitter"
    url: "https://twitter.com/jcolonfzenpr"
menu:
  main:
  - identifier: blog
    name: Blog
    params:
      class: highlight-menu-item
    url: /
    weight: 1
  - identifier: about
    name: About
    params:
      class: highlight-menu-item
    url: /about
    weight: 2
