baseURL: http://techmyth.github.io/
languageCode: en-us
copyright: "2022 Jonathan Colon All rights reserved"
title: TechMyth
theme: "PaperMod"

author:
  name: Jonathan Colon

DefaultContentLanguage: "en"

googleAnalytics: G-H243NQ4V8N

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

languages:
  es:
    languageName: Spanish
    menu:
      main:
      - identifier: blog
        name: Blog
        params:
          class: highlight-menu-item
        url: /
        weight: 1
      - identifier: about
        name: Sobre Mí
        params:
          class: highlight-menu-item
        url: /about
        weight: 2
    title: TechMyth
    weight: 2
  en:
    languageName: English
    menu:
      main:
      - identifier: blog
        name: Blog
        params:
          class: highlight-menu-item
        url: /
        weight: 1
      - identifier: about
        name: About
        params:
          class: highlight-menu-item
        url: /about
        weight: 2
    title: TechMyth
    weight: 1

params:
  defaultTheme: dark
  disableThemeToggle: true
  ShowFullTextinRSS: true
  socialIcons:
  - name: "kofi"
    url: "https://ko-fi.com/F1F8DEV80"
  - name: "twitter"
    url: "https://twitter.com/jcolonfzenpr"
  - name: "rss"
  url: "https://techmyth.github.io/index.xml"

outputs:
  home:
      - HTML
      - RSS
      - JSON
