baseURL: http://techmyth.github.io/
languageCode: en-us
title: TechMyth
theme: "PaperMod"
publishDir: "docs"
socialIcons:
  - name: "kofi"
    url: "https://ko-fi.com/F1F8DEV80"
  - name: "twitter"
    url: "https://twitter.com/jcolonfzenpr"